services:
  rss2ical:
    image: ghcr.io/sachanganesh/rss2ical:latest
    container_name: rss2ical
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.5'
        reservations:
          memory: 16M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 