version: '3.8'

services:
  rss2ical:
    build: .
    container_name: rss2ical
    restart: unless-stopped
    ports:
      - "8080:8080"  # Change external port if needed
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.5'
        reservations:
          memory: 16M
          cpus: '0.1'
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 